services:
  - type: web
    name: javanest-backend
    rootDir: backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: https://javanest-frontend.onrender.com
  - type: web
    name: JavaNestFrontend
    runtime: static
    repo: https://github.com/HypertextAssassinRajith/JavaNest
    branch: vite-express
    envVars:
    - key: VITE_API_URL
      sync: false
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    rootDir: frontend